apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ide-monitoring
  namespace: ${NAMESPACE}
  labels:
    app: ai-ide-monitoring
    version: ${VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-ide-monitoring
  template:
    metadata:
      labels:
        app: ai-ide-monitoring
        version: ${VERSION}
    spec:
      containers:
      - name: ai-ide-monitoring
        image: ghcr.io/${GITHUB_REPOSITORY}/ai-ide:${VERSION}-backend
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          value: "postgresql://aiide:$(DATABASE_PASSWORD)@postgres-postgresql:5432/ai_ide"
        - name: REDIS_URL
          value: "redis://redis-master:6379"
        - name: AI_IDE_ENV
          value: "${ENVIRONMENT}"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-ide-secrets
              key: database-password
        command: ["python", "start_monitoring.py"]
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"